### ISSUE TITLE
사용자 인가, 인증, 프로필 관리, 유효성 검사 기능 구현 (2인 협업)

### ISSUE THREAD

**Issue by jeongminy** [HwangSeungHyeon/bunnies#4]
## Description
사용자 인가, 인증, 프로필 관리, 유효성검사 기능 구현을 목표로 합니다.

## Todo
- [x] 회원가입 : 성공메세지, 2.상태코드반환(201)
- [x] 로그인기능 : 로그인 성공 시, 로그인에 성공한 유저의 정보와 JWT를 활용하여 토큰을 발급하고, 발급한 토큰을 Header에 추가하고 성공했다는 메시지, 상태코드와 함께 Client에 반환한다.
- [x] 상대프로필 조회
- [x] 내프로필 조회

- [x] 내프로필 수정 
- [x] 내프로필 수정 : 1. 비밀번호 수정 시에는 비밀번호를 한 번 더 입력받는 과정이 필요하다.
- [x] 내프로필 수정 : 2. 최근 3번안에 사용한 비밀번호는 사용할 수 없도록 제한한다.

- [x] 내프로필 삭제 (회원탈퇴)

- [x] 유효성검사 - nickname : 최소 4자 이상, 10자 이하이며 알파벳 소문자(a~z), 숫자(0~9)
- [x] 유효성검사 - email : 1. 중복검사 + 2. 이메일형식인지 확인
- [x] 유효성검사 - password : 최소 8자 이상, 15자 이하이며 알파벳 대소문자(a~z, A~Z), 숫자(0~9), 특수문자

- [x] 인가 - 관리자(ADMIN) :  ADMIN 회원은 모든 게시글, 댓글을 수정 / 삭제 가능하다.
- [x] 인가 - 유저(USER)

## ETC
강군호님과 한정민님의 협업으로 구현 하고자 합니다.
